### ISSUE TITLE
【Rails Git】git push したら、脆弱性の警告がでた

### ISSUE THREAD

**Issue by sice11** [sice11/STUDY_1#1]
![image](https://user-images.githubusercontent.com/61615289/85969935-07b29100-ba04-11ea-963b-7c54c6882a7d.png)

![image](https://user-images.githubusercontent.com/61615289/85969887-e782d200-ba03-11ea-8e82-ce024d71ea01.png)

**Comment by good1luck21** [comment]
railsに入っているnpmのパッケージのバージョンが古いとこういうエラーが出ることありますが、
特に問題ありませんのでこのまま進めていただいて大丈夫です。

**Comment by sice11** [comment]
ありがとうございます。
